//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_OrdersSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ns_ordersEntities : DbContext
    {
        public ns_ordersEntities()
            : base("name=ns_ordersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<order> orders { get; set; }
        public DbSet<quote> quotes { get; set; }
        public DbSet<user> users { get; set; }
    
        public virtual ObjectResult<sp_orders_Result> sp_orders(string i_accion, Nullable<int> i_order, Nullable<System.DateTime> i_date, string i_client_name, string i_phone, string i_product_description, Nullable<double> i_price, Nullable<double> i_anticipe, string i_observation, Nullable<bool> i_state, Nullable<int> i_user_owner)
        {
            var i_accionParameter = i_accion != null ?
                new ObjectParameter("i_accion", i_accion) :
                new ObjectParameter("i_accion", typeof(string));
    
            var i_orderParameter = i_order.HasValue ?
                new ObjectParameter("i_order", i_order) :
                new ObjectParameter("i_order", typeof(int));
    
            var i_dateParameter = i_date.HasValue ?
                new ObjectParameter("i_date", i_date) :
                new ObjectParameter("i_date", typeof(System.DateTime));
    
            var i_client_nameParameter = i_client_name != null ?
                new ObjectParameter("i_client_name", i_client_name) :
                new ObjectParameter("i_client_name", typeof(string));
    
            var i_phoneParameter = i_phone != null ?
                new ObjectParameter("i_phone", i_phone) :
                new ObjectParameter("i_phone", typeof(string));
    
            var i_product_descriptionParameter = i_product_description != null ?
                new ObjectParameter("i_product_description", i_product_description) :
                new ObjectParameter("i_product_description", typeof(string));
    
            var i_priceParameter = i_price.HasValue ?
                new ObjectParameter("i_price", i_price) :
                new ObjectParameter("i_price", typeof(double));
    
            var i_anticipeParameter = i_anticipe.HasValue ?
                new ObjectParameter("i_anticipe", i_anticipe) :
                new ObjectParameter("i_anticipe", typeof(double));
    
            var i_observationParameter = i_observation != null ?
                new ObjectParameter("i_observation", i_observation) :
                new ObjectParameter("i_observation", typeof(string));
    
            var i_stateParameter = i_state.HasValue ?
                new ObjectParameter("i_state", i_state) :
                new ObjectParameter("i_state", typeof(bool));
    
            var i_user_ownerParameter = i_user_owner.HasValue ?
                new ObjectParameter("i_user_owner", i_user_owner) :
                new ObjectParameter("i_user_owner", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_orders_Result>("sp_orders", i_accionParameter, i_orderParameter, i_dateParameter, i_client_nameParameter, i_phoneParameter, i_product_descriptionParameter, i_priceParameter, i_anticipeParameter, i_observationParameter, i_stateParameter, i_user_ownerParameter);
        }
    
        public virtual ObjectResult<sp_quotes_Result> sp_quotes(string i_accion, Nullable<int> i_quote, Nullable<System.DateTime> i_date, string i_client_name, string i_phone, string i_detail, Nullable<double> i_price, string i_supplier, Nullable<int> i_user_owner)
        {
            var i_accionParameter = i_accion != null ?
                new ObjectParameter("i_accion", i_accion) :
                new ObjectParameter("i_accion", typeof(string));
    
            var i_quoteParameter = i_quote.HasValue ?
                new ObjectParameter("i_quote", i_quote) :
                new ObjectParameter("i_quote", typeof(int));
    
            var i_dateParameter = i_date.HasValue ?
                new ObjectParameter("i_date", i_date) :
                new ObjectParameter("i_date", typeof(System.DateTime));
    
            var i_client_nameParameter = i_client_name != null ?
                new ObjectParameter("i_client_name", i_client_name) :
                new ObjectParameter("i_client_name", typeof(string));
    
            var i_phoneParameter = i_phone != null ?
                new ObjectParameter("i_phone", i_phone) :
                new ObjectParameter("i_phone", typeof(string));
    
            var i_detailParameter = i_detail != null ?
                new ObjectParameter("i_detail", i_detail) :
                new ObjectParameter("i_detail", typeof(string));
    
            var i_priceParameter = i_price.HasValue ?
                new ObjectParameter("i_price", i_price) :
                new ObjectParameter("i_price", typeof(double));
    
            var i_supplierParameter = i_supplier != null ?
                new ObjectParameter("i_supplier", i_supplier) :
                new ObjectParameter("i_supplier", typeof(string));
    
            var i_user_ownerParameter = i_user_owner.HasValue ?
                new ObjectParameter("i_user_owner", i_user_owner) :
                new ObjectParameter("i_user_owner", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_quotes_Result>("sp_quotes", i_accionParameter, i_quoteParameter, i_dateParameter, i_client_nameParameter, i_phoneParameter, i_detailParameter, i_priceParameter, i_supplierParameter, i_user_ownerParameter);
        }
    
        public virtual ObjectResult<sp_users_Result> sp_users(string i_accion, Nullable<int> i_user, string i_login, string i_name, string i_paterno, string i_materno, string i_password, Nullable<bool> i_master, Nullable<bool> i_enable)
        {
            var i_accionParameter = i_accion != null ?
                new ObjectParameter("i_accion", i_accion) :
                new ObjectParameter("i_accion", typeof(string));
    
            var i_userParameter = i_user.HasValue ?
                new ObjectParameter("i_user", i_user) :
                new ObjectParameter("i_user", typeof(int));
    
            var i_loginParameter = i_login != null ?
                new ObjectParameter("i_login", i_login) :
                new ObjectParameter("i_login", typeof(string));
    
            var i_nameParameter = i_name != null ?
                new ObjectParameter("i_name", i_name) :
                new ObjectParameter("i_name", typeof(string));
    
            var i_paternoParameter = i_paterno != null ?
                new ObjectParameter("i_paterno", i_paterno) :
                new ObjectParameter("i_paterno", typeof(string));
    
            var i_maternoParameter = i_materno != null ?
                new ObjectParameter("i_materno", i_materno) :
                new ObjectParameter("i_materno", typeof(string));
    
            var i_passwordParameter = i_password != null ?
                new ObjectParameter("i_password", i_password) :
                new ObjectParameter("i_password", typeof(string));
    
            var i_masterParameter = i_master.HasValue ?
                new ObjectParameter("i_master", i_master) :
                new ObjectParameter("i_master", typeof(bool));
    
            var i_enableParameter = i_enable.HasValue ?
                new ObjectParameter("i_enable", i_enable) :
                new ObjectParameter("i_enable", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_users_Result>("sp_users", i_accionParameter, i_userParameter, i_loginParameter, i_nameParameter, i_paternoParameter, i_maternoParameter, i_passwordParameter, i_masterParameter, i_enableParameter);
        }
    }
}
