//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_OrdersSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.orders = new HashSet<order>();
            this.quotes = new HashSet<quote>();
        }
    
        public int us_user { get; set; }
        public string us_login { get; set; }
        public string us_name { get; set; }
        public string us_paterno { get; set; }
        public string us_materno { get; set; }
        public string us_password { get; set; }
        public Nullable<bool> us_master { get; set; }
        public Nullable<bool> us_enable { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<quote> quotes { get; set; }
    }
}
